name: Update S3 buckets

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  update_s3:
    name: Update S3 buckets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract data from JSON
        run: |
          mkdir out
          cat EXD_supply.json | jq '{"circulating-supply":.["circulating-supply"]}' > out/circulating-supply
          cat EXD_supply.json | jq '{"max-supply":.["max-supply"]}' > out/max-supply
          cat EXD_supply.json | jq '{"total-supply":.["total-supply"]}' > out/total-supply
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.4.0
        with:
          provider: scaleway
          region: "fr-par"
          access_key: ${{ secrets.S3_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      - name: Upload files
        run: |
          s3cmd put out/circulating-supply --mime-type 'application/json' --acl-public s3://${{ secrets.S3_BUCKET }}/circulating-supply
          s3cmd put out/max-supply --mime-type 'application/json' --acl-public s3://${{ secrets.S3_BUCKET }}/max-supply
          s3cmd put out/total-supply --mime-type 'application/json' --acl-public s3://${{ secrets.S3_BUCKET }}/total-supply
      - name: Send a message to slack if CI has failed
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": ":x: The CI _'${{ github.workflow }}'_ of repository _${{ github.repository }}_ has failed. Link to PR/commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
